name: MedNow Cron

on:
  schedule:
    - cron: "*/1 * * * *"   # Executa todo minuto
  workflow_dispatch:       # Permite rodar manualmente tamb√©m

jobs:
  ping_scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Chamar API do MedNow Scheduler
        run: |
          echo "Chamando https://mednow-one.vercel.app/api/scheduler/alarme"
          curl -X GET "https://mednow-one.vercel.app/api/scheduler/alarme"
